//
//  DescriptionOfTheCity.swift
//  swiftUIProject
//
//  Created by Надежда Клименко on 14.11.21.
//

import Foundation

enum DescriptionOfTheCity: String {
    case lisbon = "Lisbon, the capital of Portugal, is one of Europe's most beautiful and cosmopolitan cities. Set over a series of hills near the mouth of the River Tagus, it's a place inextricably linked with the sea. Intrepid navigators embarked from here in the 15th and 16th centuries to sail unknown waters and chart new lands, and the legacy of this golden Age of Discovery underpins much of the city's culture and heritage. Lisbon is a colorful and vibrant destination. Renowned for its warm and sunny disposition, the city is blessed with a wealth of historic monuments, world-class museums, and a host of other fabulous things to do that can easily be worked into a single or multi-day itinerary. You can explore the narrow streets of the old quarter, stroll the riverbank promenade, or wander through verdant parks and gardens. In fact, enjoy Lisbon like the locals do, at an easy and unhurried pace, and you'll quickly fall for its welcoming character and beguiling charm. For ideas on the best places to visit while you're here, see our list of the top tourist attractions in Lisbon."
    case madrid = "Madrid is the capital of Spain, and is home to the Spanish Royal family as well as the Spanish Government. It is a modern metropolitan city and an economical and industrial center of Spain, and, with its population of nearly 3,5 million people, is also the biggest city in Spain. It is located in the centre of the Iberian Peninsula, and is surrounded by mountains and natural parks. Although it is located in the centre of the country, it has traditionally been the hub between different areas of Spain and is therefore connected to all major Spanish cities by train, road or air. Madrid has a lot of interesting attractions that offer both culture and amusement. The city is full of great monuments, like the royal palace, the Plaza Mayor or the many statuettes, and for people interested in art, the museums Del Prado, Reina Sofia or Thyssen have some of the most fantastic collections of famous Spanish painters like Velazquez, Goya, Picasso or Miro. If you like to be entertained, Madrid has two big amusements parks (including the new Warner Bros park) and there are regular international concerts, big flea markets, parades and other activities going on. To sport enthusiasts Madrid can offer everything from skiing (only 1 hour away by bus) during the winter, to golf all year round, as well as international sporting events and the possibility to practice nearly any sport at the University facilities. If you like going out at night, Madrid has a very interesting nightlife throughout the whole week and which is available all year round. You can either go out for a tapa (Spanish snack), eat at a very nice restaurant, go to the cinema or one of the many theatres, or find nearly any type of bar or disco."
    case portofino = "Portofino is a fishing town on the coast of Italy, located southeast of Genoa. Pastel-colored houses, luxury shops and seafood restaurants surround the small cobbled Piazzetta square. It offers a view of the port, where expensive yachts are moored. From here you can get to Brown Castle, a fortress of the XVI century, where the art museum is now located. The fortress walls offer panoramic views of the city and the Ligurian Sea. One of the most popular resort towns on the Italian Riviera, little Portofino has just over 500 permanent residents. But that all changes on summer days when the sun is shining and the yachting set drops anchor in the harbor to wander about. Boutiques, art galleries, cafes and restaurants line the tiny streets. Diving, hiking and beach-going are popular local pastimes, and there are even some historic sights like the Church of St. Martin (Divo Martino) and the Castello Brown hilltop fortress."
    case USAGrandCanyon = "The Grand Canyon in Arizona is a unique natural formation. Bands of geological layers appear on the red rocks, demonstrating millions of years of earth's history in cross-section. The canyon, huge in its area, stretches for 446 km, its width ranges from 6 to 29 km, and its depth is up to 1.8 km. Most of this territory is part of the national park. Here you can admire the rapid rapids of the Colorado River and stunning views. Of all Grand Canyon facts, this one is pretty cool – no pun intended. Sudden changes in elevation have an enormous impact on temperature and precipitation, so the weather you're experiencing could vary drastically depending on where you are in the Grand Canyon. The coldest, wettest weather station in the region is the Bright Angel Ranger Station on the North Rim, while the hottest (and one of the driest) is just 8 miles away at Phantom Ranch."
    case USALas_Vegase = "Las Vegas is a resort city in the Mojave Desert in Nevada, which is famous for its vibrant nightlife. There are many round-the-clock casinos and other entertainment venues. The main street of the city, the Las Vegas Strip, stretches for almost seven kilometers. There are themed hotels, musical fountains, as well as copies of the Egyptian pyramids, the Venetian Grand Canal and the Paris Eiffel Tower."
    case USANiagaraFalls = "Niagara Falls is located on the border of Canada (Ontario) and the United States (New York state), on the Niagara River of the same name, which connects Lake Erie and Ontario, which are part of the Great North American Lakes system. On the coast of the river next to the waterfall from both countries there are two cities with the same name Niagara Falls. In fact, Niagara Falls are three separate waterfalls - American Falls, Horseshoe Falls and Bridal Veil Falls. Canadians are lucky, because the largest waterfall 'Horseshoe' is located on the territory of their country. Waterfalls 'Bridal Veil' and 'American' are located in the United States. And by the way, most tourists agree that the view from the Canadian side is more impressive than from the American side. The waterfalls are separated by a chain of small islets, of which the most famous is Donkey Island on the Canadian side. Almost 90% of the Niagara River's water mass falls from the Horseshoe Waterfall, and only 10% passes through American territory."
    
    
}
