# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Weather' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Weather
  pod 'Alamofire', '~> 5.4'
  pod 'AlamofireNetworkActivityLogger', '~> 3.4'
  pod 'TextFieldEffects'
  pod 'RealmSwift', '~>10'
  pod 'Firebase/Analytics'
  pod 'Firebase/Crashlytics'
  pod 'Firebase/RemoteConfig'
  pod 'GoogleMaps', '5.1.0'
  pod 'RxSwift', '6.2.0'
  pod 'RxCocoa', '6.2.0'
  pod 'NVActivityIndicatorView'
 

end
